name: tixid_lear_raisya
description: "A cinema tickets booking app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  google_fonts: 6.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/static/Montserrat-Medium.ttf
          weight: 500
